version: '3'
services:
  drip:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    restart: always
    ports:
      # Default svc port is 8001
      - 8001:8001
    environment:
      DATABASE_DSN: "${DATABASE_DSN}"
      CONFIG_PATH: /config_path
      API_BIND_ADDR: "${API_BIND_ADDR}"
      API_PORT: "${API_PORT}"
      FLIPSIDE_API_KEY: "${FLIPSIDE_API_KEY}"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - config_path

configs:
  config_path:
    file: ./config/config.json